const fs=require('node:fs');
const origin='https://util.oa.gg';
const publisher='ca-pub-8194376114167709';
const navigation='<header><a class="brand" href="/">util.oa.gg<span>작은 도구, 바로 해결</span></a><nav aria-label="도구 탐색"><a href="/">이미지 압축</a><a href="/text-counter/">글자 수</a><a href="/data-size/">용량 변환</a></nav><span class="privacy">● 내 기기에서 처리</span></header>';
const discovery='<section class="discover" aria-label="다른 유틸리티"><h2>다른 작업도 바로 해결하세요</h2><div class="cards"><a href="/"><strong>이미지 용량 압축</strong><span>사진을 원하는 KB·MB 이하로</span></a><a href="/text-counter/"><strong>글자 수 계산</strong><span>공백 포함·제외, UTF-8 바이트</span></a><a href="/data-size/"><strong>파일 용량 단위 변환</strong><span>KB·MB와 KiB·MiB를 분명하게</span></a></div></section>';
const footer='<footer class="site-footer"><a href="/about/">사이트 소개</a><a href="/privacy/">개인정보 안내</a><a href="https://github.com/jhs512/util.oa.gg/issues">문의·오류 제보</a><span>util.oa.gg · 가입 없이 바로 쓰는 도구</span></footer>';
const metadata=(title,description,url)=>`<meta name="description" content="${description}"><title>${title} | util.oa.gg</title><link rel="canonical" href="${url}"><meta name="google-adsense-account" content="${publisher}"><meta property="og:type" content="website"><meta property="og:title" content="${title} | util.oa.gg"><meta property="og:description" content="${description}"><meta property="og:url" content="${url}"><meta property="og:site_name" content="util.oa.gg">`;
const extra='<section class="guide"><h2>사진을 100 KB 또는 200 KB 이하로 맞추는 방법</h2><p>사진을 선택한 뒤 제출처의 최대 용량을 입력하세요. 압축 결과는 실제 바이트 수로 확인합니다. JPG를 요구하는 제출처에서는 저장 형식을 JPG로 바꾸고, 다운로드 전에 글자와 얼굴이 잘 보이는지 확인하세요.</p><h2>용량이 줄지 않을 때는?</h2><p>투명한 PNG는 사진용 JPG보다 클 수 있습니다. 배경이 필요하면 JPG, 투명도를 유지하려면 WebP를 시도하세요. 목표가 지나치게 작으면 품질과 크기 하한 때문에 실패할 수 있습니다. 도구는 실패를 목표 달성으로 표시하지 않습니다.</p><h2>KB와 픽셀 크기는 다릅니다</h2><p>파일 용량을 줄여도 제출처의 가로·세로 픽셀 조건을 자동으로 만족하지는 않습니다. 결과에 표시된 픽셀 크기와 파일 형식을 별도로 확인하세요. 용량 제한 단위가 헷갈리면 <a href="/data-size/">용량 단위 변환</a>을 이용하세요.</p></section>';
let image=fs.readFileSync(require('node:path').join(__dirname,'index.html'),'utf8');
image=image.replace(/<meta name="description"[^>]*><title>.*?<\/title>/,metadata('이미지 용량 압축 — 사진 100KB·200KB 이하','목표 KB·MB 이하로 JPG, PNG, WebP 이미지를 압축하고 크기·화질을 비교하세요. 이미지는 브라우저에서 처리합니다.',origin+'/'));
image=image.replace(/<header>.*?<\/header>/s,navigation).replace('href="style.css"','href="/style.css"').replace('src="app.js"','src="/app.js"');
image=image.replace('</main>',extra+discovery+footer+'</main>');
const shell=(slug,title,description,body)=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${metadata(title,description,origin+slug)}<link rel="stylesheet" href="/style.css"><script type="module" src="/hub-tools.js"></script></head><body><main>${navigation}${body}${discovery}${footer}</main></body></html>`;
const pages={
  'index.html':image,
  'text-counter/index.html':shell('/text-counter/','글자 수 계산 — 공백 제외·UTF-8 바이트','텍스트를 붙여넣으면 공백 포함·제외 글자 수, 단어 수와 UTF-8 바이트 수를 즉시 계산합니다.',`<section class="intro"><p class="eyebrow">붙여넣으면 바로 계산</p><h1>글자 수와 바이트를<br><em>한눈에 확인하세요.</em></h1><p>입력한 내용은 저장하거나 서버로 보내지 않습니다.</p></section><section class="simple-tool"><label for="text-input">계산할 텍스트</label><textarea id="text-input" rows="8" placeholder="여기에 글을 입력하거나 붙여넣으세요"></textarea><button id="clear" type="button">내용 지우기</button><dl class="metrics" aria-live="polite"><div><dt>공백 포함 글자</dt><dd id="characters">0</dd></div><div><dt>공백 제외 글자</dt><dd id="no-spaces">0</dd></div><div><dt>UTF-8 바이트</dt><dd id="bytes">0</dd></div><div><dt>단어 (공백 기준)</dt><dd id="words">0</dd></div></dl></section><section class="guide"><h2>글자 수와 바이트 수가 다른 이유</h2><p>UTF-8에서 일반적인 한글 음절은 3바이트, 영문자는 1바이트를 사용합니다. 이모지와 조합 문자는 더 복잡할 수 있습니다. 이 도구는 사용자가 보는 문자 단위로 글자 수를 세며 줄바꿈도 공백 포함 글자에 셉니다.</p><h2>제출처의 계산 방식도 확인하세요</h2><p>공백 제외는 줄바꿈과 탭도 제외합니다. 단어 수는 공백으로 구분한 묶음 수이며 언어학적인 단어 수가 아닙니다. 제출처가 UTF-16 코드 단위나 다른 인코딩을 쓰면 결과가 다를 수 있습니다.</p></section>`),
  'data-size/index.html':shell('/data-size/','파일 용량 단위 변환 — KB·MB·KiB·MiB','파일 크기를 바이트, KB, MB, KiB, MiB로 변환하고 십진 단위와 이진 단위의 차이를 확인하세요.',`<section class="intro"><p class="eyebrow">파일 제한, 단위부터 정확하게</p><h1>KB와 KiB의 차이,<br><em>바로 계산하세요.</em></h1><p>파일을 선택할 필요 없이 숫자만 입력하세요.</p></section><section class="simple-tool"><label for="quantity">변환할 용량</label><div class="target"><input id="quantity" type="number" min="0" step="any" value="1"><label class="sr" for="from-unit">입력 단위</label><select id="from-unit"><option value="1">B</option><option value="1000">KB</option><option value="1000000" selected>MB</option><option value="1024">KiB</option><option value="1048576">MiB</option></select></div><p id="conversion-status" role="status"></p><dl class="metrics"><div><dt>바이트 (B)</dt><dd data-factor="1"></dd></div><div><dt>KB · 1,000 B</dt><dd data-factor="1000"></dd></div><div><dt>MB · 1,000,000 B</dt><dd data-factor="1000000"></dd></div><div><dt>KiB · 1,024 B</dt><dd data-factor="1024"></dd></div><div><dt>MiB · 1,048,576 B</dt><dd data-factor="1048576"></dd></div></dl></section><section class="guide"><h2>1 MB와 1 MiB는 같지 않습니다</h2><p>MB는 1,000,000바이트이고 MiB는 1,048,576바이트입니다. 일부 서비스는 KB라고 표시하면서 1,024바이트 기준을 쓰기도 합니다. 제출처 안내를 우선 확인하세요.</p><h2>사진 용량을 실제로 줄이려면</h2><p>이 도구는 단위를 변환하며 파일을 변경하지 않습니다. 업로드 제한에 맞춰 사진을 줄이려면 <a href="/">이미지 압축기</a>에서 목표 용량을 설정하세요. 소수 결과는 최대 여섯 자리로 반올림해 표시합니다.</p></section>`),
  'privacy/index.html':shell('/privacy/','개인정보 처리 안내','util.oa.gg의 브라우저 로컬 처리, 저장하지 않는 입력과 호스팅·광고 준비 상태를 안내합니다.',`<section class="guide"><h1>개인정보 안내</h1><p>최종 갱신: 2026-10-01</p><h2>이미지와 텍스트는 내 기기에서 처리합니다</h2><p>파일·파일명·입력한 글을 서버로 전송하거나 저장하지 않습니다. 입력을 브라우저 저장소에 보관하지 않고 탭을 닫으면 작업 상태가 사라집니다.</p><h2>웹사이트 접속</h2><p>정적 사이트는 Cloudflare에서 제공합니다. 페이지 접속 시 IP 주소, 브라우저 및 요청 정보는 호스팅 제공자에게 전달될 수 있습니다. 이 사이트에는 별도의 분석 SDK나 회원 계정이 없습니다.</p><h2>광고 준비 상태</h2><p>Google AdSense의 실제 게시자 계정에 연결할 수 있도록 확인 메타 태그와 ads.txt를 제공합니다. 현재 사이트는 광고 승인이 완료되지 않았고 광고 스크립트를 실행하지 않습니다. 광고를 활성화할 때는 Google이 사용하는 쿠키·정보 처리와 적용 지역의 동의 방식을 이 안내에 반영합니다.</p><h2>문의</h2><p><a href="https://github.com/jhs512/util.oa.gg/issues">GitHub 문의</a>에 개인정보나 원본 이미지를 첨부하지 않고 현상을 설명해주세요.</p></section>`),
  'about/index.html':shell('/about/','사이트 소개 — 가입 없이 쓰는 작은 도구','util.oa.gg는 이미지 용량 압축, 글자 수 계산과 파일 용량 단위 변환을 제공하는 한국어 유틸리티 허브입니다.',`<section class="guide"><h1>작은 도구, 바로 해결.</h1><p>util.oa.gg는 하나의 작업을 빠르게 해결하는 한국어 유틸리티 허브입니다. 검색에서 도구로 바로 들어오고, 필요한 다른 도구로 이동할 수 있습니다.</p><h2>지금 사용할 수 있는 도구</h2><p>목표 용량 이미지 압축, 공백 포함·제외 글자 수 계산, 파일 용량 단위 변환을 제공합니다. 이미지와 텍스트 처리는 브라우저에서 이뤄집니다.</p><h2>확인 가능한 결과를 우선합니다</h2><p>이미지 압축은 실제 용량과 픽셀 크기, 목표 달성 여부를 표시합니다. 달성할 수 없는 목표와 제출처마다 다른 조건도 알려드립니다. 계산 결과나 화질은 실제 사용 목적에 맞게 확인해주세요.</p><p><a href="https://github.com/jhs512/util.oa.gg">소스 코드</a>와 <a href="https://github.com/jhs512/util.oa.gg/issues">오류 제보</a>를 통해 개선합니다.</p></section>`)
};
for(const name of Object.keys(pages)){
  pages[name]=pages[name].replace(/href="\/(?!\/)([^\"]*)"/g,(match,pathname)=>pathname==='style.css'?match:`href="${origin}/${pathname}"`);
}
module.exports={pages};
