const fs=require('node:fs');
const origin='https://util.oa.gg';
const publisher='ca-pub-8194376114167709';
const navigation='<header><a class="brand" href="/">util.oa.gg<span>Useful tools. Instant results.</span></a><nav aria-label="Tools"><a href="/">Image compressor</a><a href="/text-counter/">Character counter</a><a href="/data-size/">File size converter</a></nav><span class="privacy">● On-device processing</span></header>';
const discovery='<section class="discover" aria-label="More tools"><h2>More free tools</h2><div class="cards"><a href="/"><strong>Image compressor</strong><span>Reduce JPG, PNG or WebP to a target KB or MB</span></a><a href="/text-counter/"><strong>Character and byte counter</strong><span>Count characters, words and UTF-8 bytes</span></a><a href="/data-size/"><strong>File size converter</strong><span>Convert bytes, KB, MB, KiB and MiB</span></a></div></section>';
const footer='<footer class="site-footer"><a href="/about/">About</a><a href="/privacy/">Privacy</a><a href="https://github.com/jhs512/util.oa.gg/issues">Report an issue</a><span>util.oa.gg · Free tools, no signup</span></footer>';
const metadata=(title,description,url)=>`<meta name="description" content="${description}"><title>${title} | util.oa.gg</title><link rel="canonical" href="${url}"><meta name="google-adsense-account" content="${publisher}"><meta property="og:type" content="website"><meta property="og:title" content="${title} | util.oa.gg"><meta property="og:description" content="${description}"><meta property="og:url" content="${url}"><meta property="og:site_name" content="util.oa.gg"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${title} | util.oa.gg"><meta name="twitter:description" content="${description}">`;
const extra='<section class="guide"><h2>How to compress an image to 100 KB or 200 KB</h2><ol><li>Choose a JPG, PNG or static WebP image.</li><li>Enter your upload limit in KB or MB, or choose a preset.</li><li>Select an output format and compress. Check the actual file size and preview before downloading.</li></ol><p>Use JPG when a form requires a JPEG file. WebP can keep transparency; JPG turns transparent areas white. An image that meets the byte limit may still need different pixel dimensions for your destination.</p><h2>Why is my image still above the target?</h2><p>Some targets are too small to reach within the quality and dimension limits. PNG compression reduces dimensions rather than changing a quality setting. Try WebP, allow resizing or increase the target. The tool clearly marks results that exceed your limit.</p><h2>Does image compression upload my photo?</h2><p>No. Compression and previews run in your browser. Your image is not sent to a server. You can compare the original and compressed image before saving.</p><h2>Does this reduce image dimensions too?</h2><p>When resizing is allowed, the tool can reduce width and height to meet the file size target. File size and pixel dimensions are different requirements. Check both in the result. Use the <a href="/data-size/">file size converter</a> if you need to compare KB, MB and binary units.</p></section>';
let image=fs.readFileSync(require('node:path').join(__dirname,'index.html'),'utf8');
image=image.replace(/<meta name="description"[^>]*><title>.*?<\/title>/,metadata('Image Compressor to 100 KB, 200 KB or Any Target Size','Compress JPG, PNG and WebP images to a target KB or MB. Compare quality and download the result. Free, browser-based and no image uploads.',origin+'/'));
image=image.replace(/<header>.*?<\/header>/s,navigation).replace('href="style.css"','href="/style.css"').replace('src="app.js"','src="/app.js"');
image=image.replace('</main>',extra+discovery+footer+'</main>');
const shell=(slug,title,description,body)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${metadata(title,description,origin+slug)}<link rel="stylesheet" href="/style.css"><script type="module" src="/hub-tools.js"></script></head><body><main>${navigation}${body}${discovery}${footer}</main></body></html>`;
const pages={
 'index.html':image,
 'text-counter/index.html':shell('/text-counter/','Character Counter, Word Count and UTF-8 Byte Counter','Count characters with and without spaces, words and UTF-8 bytes instantly. Free online text counter with local processing and no signup.',`<section class="intro"><p class="eyebrow">Paste text. Get the numbers.</p><h1>Character and word count.<br><em>UTF-8 bytes, too.</em></h1><p>Your text stays in this browser. Nothing is uploaded or saved.</p></section><section class="simple-tool"><label for="text-input">Text to count</label><textarea id="text-input" rows="8" placeholder="Type or paste your text here"></textarea><button id="clear" type="button">Clear text</button><dl class="metrics" aria-live="polite"><div><dt>Characters with spaces</dt><dd id="characters">0</dd></div><div><dt>Characters without spaces</dt><dd id="no-spaces">0</dd></div><div><dt>UTF-8 bytes</dt><dd id="bytes">0</dd></div><div><dt>Words (whitespace-separated)</dt><dd id="words">0</dd></div></dl></section><section class="guide"><h2>How to count characters and words</h2><p>Type or paste text into the box. Counts update immediately. Use the character count for a length limit, and the UTF-8 byte count when a form or system limits encoded data size.</p><h2>Why are characters and bytes different?</h2><p>Basic Latin letters take one byte in UTF-8. Accented letters, other writing systems and emoji can take more. This counter counts visible character clusters, so a combined emoji may count as one character while using several bytes.</p><h2>What counts as a space or a word?</h2><p>The count with spaces includes line breaks and tabs. The count without spaces excludes whitespace. Words are groups separated by whitespace, rather than language-specific dictionary words. A destination that counts UTF-16 code units may return a different character count.</p><p>To compare byte limits in KB and MB, use the <a href="/data-size/">file size converter</a>.</p></section>`),
 'data-size/index.html':shell('/data-size/','File Size Converter: Bytes, KB, MB, KiB and MiB','Convert file size between bytes, KB, MB, KiB and MiB. Compare decimal and binary units instantly with this free online data size calculator.',`<section class="intro"><p class="eyebrow">Make sense of upload limits</p><h1>Convert file sizes.<br><em>Know your KB from KiB.</em></h1><p>Enter a number. No file upload needed.</p></section><section class="simple-tool"><label for="quantity">File size to convert</label><div class="target"><input id="quantity" type="number" min="0" step="any" value="1"><label class="sr" for="from-unit">Input unit</label><select id="from-unit"><option value="1">B</option><option value="1000">KB</option><option value="1000000" selected>MB</option><option value="1024">KiB</option><option value="1048576">MiB</option></select></div><p id="conversion-status" role="status"></p><dl class="metrics"><div><dt>Bytes (B)</dt><dd data-factor="1"></dd></div><div><dt>KB · 1,000 B</dt><dd data-factor="1000"></dd></div><div><dt>MB · 1,000,000 B</dt><dd data-factor="1000000"></dd></div><div><dt>KiB · 1,024 B</dt><dd data-factor="1024"></dd></div><div><dt>MiB · 1,048,576 B</dt><dd data-factor="1048576"></dd></div></dl></section><section class="guide"><h2>How many KB are in 1 MB?</h2><p>Using decimal units, 1 MB equals 1,000 KB or 1,000,000 bytes. Using binary units, 1 MiB equals 1,024 KiB or 1,048,576 bytes. Select the exact unit used by your destination.</p><h2>What is the difference between KB and KiB?</h2><p>KB is 1,000 bytes. KiB is 1,024 bytes. Some services display KB while calculating with a 1,024-byte basis, so check their instructions when a file is close to an upload limit.</p><h2>Does converting units make my file smaller?</h2><p>No. This calculator expresses the same size in different units. To reduce an image file, use the <a href="/">image compressor</a>. To measure text before converting, use the <a href="/text-counter/">UTF-8 byte counter</a>. Results are rounded to at most six decimal places.</p></section>`),
 'privacy/index.html':shell('/privacy/','Privacy Policy','How util.oa.gg processes images and text locally, handles website requests and prepares for advertising.',`<section class="guide"><h1>Privacy policy</h1><p>Last updated: October 1, 2026</p><h2>Images and text stay on your device</h2><p>Files, filenames and text inputs are processed in your browser. We do not upload or store these inputs on a server or in browser storage. Closing the tab clears the working state.</p><h2>Website requests</h2><p>Cloudflare hosts this static website. When you load a page, your IP address, browser and request information may be handled by the hosting provider. The site has no separate analytics SDK or user accounts.</p><h2>Advertising status</h2><p>The site provides a publisher verification meta tag and ads.txt for Google AdSense. Advertising approval is not complete and no ad scripts run. Before advertising is enabled, this policy will describe the relevant Google cookie and data handling, along with consent arrangements for applicable regions.</p><h2>Contact</h2><p><a href="https://github.com/jhs512/util.oa.gg/issues">Report a privacy concern on GitHub</a>. Do not post personal information or original images in a public issue.</p></section>`),
 'about/index.html':shell('/about/','About Our Free Browser-Based Tools','util.oa.gg offers free image compression, character and UTF-8 byte counting, and file size conversion without signup.',`<section class="guide"><h1>Useful tools. Instant results.</h1><p>util.oa.gg helps you finish small tasks quickly. Open a tool, get your result and discover other useful tools through the shared navigation.</p><h2>Tools you can use today</h2><p>Compress an image to a target file size, count characters and UTF-8 bytes, or convert file size units. Image and text processing runs in your browser.</p><h2>Results you can check</h2><p>The image compressor reports actual output bytes, dimensions and whether your target was reached. Unreachable targets are clearly marked. Always check output quality and the requirements of your destination.</p><p>View the <a href="https://github.com/jhs512/util.oa.gg">source code</a> or <a href="https://github.com/jhs512/util.oa.gg/issues">report an issue</a> to help improve the tools.</p></section>`)
};
for(const name of Object.keys(pages)){
 pages[name]=pages[name].replace(/href="\/(?!\/)([^\"]*)"/g,(match,pathname)=>pathname==='style.css'?match:`href="${origin}/${pathname}`+'"');
}
module.exports={pages};
