const input=(id,label,type='number',value='')=>`<label for="${id}">${label}</label><input id="${id}" type="${type}" value="${value}" ${type==='number'?'step="any"':''}>`;
const select=(id,label,options)=>`<label for="${id}">${label}</label><select id="${id}">${options.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select>`;
const area=(id,label,value='',readonly=false)=>`<label for="${id}">${label}</label><textarea id="${id}" rows="5" ${readonly?'readonly':''} spellcheck="false">${value}</textarea>`;
const action=(id,text)=>`<button id="${id}" type="button">${text}</button>`;
const result='<output id="tool-result" aria-live="polite"></output>';
const tools=[
 ['calendar','Monthly Calendar','Browse any month, choose Sunday or Monday first, and print a clean calendar.',input('month','Month','month')+select('week-start','Week starts on',[['0','Sunday'],['1','Monday']])+`<div class="actions">${action('previous','Previous month')}${action('today','This month')}${action('next','Next month')}${action('print','Print calendar')}</div><h2 id="month-title"></h2><div id="calendar-grid" class="calendar-grid" role="grid" aria-label="Monthly calendar"></div>`,'Choose a month to see its weekdays and dates. Today is highlighted using your device date. Use Print calendar for a paper copy.','This is a Gregorian calendar. Public holidays and personal events are not included. The weekday layout follows your selected first day.'],
 ['date-calculator','Date Difference and Date Calculator','Count days between two dates or add and subtract days from a starting date.',input('date-start','Start date','date')+input('date-end','End date','date')+input('date-offset','Days to add (negative to subtract)','number','7')+result,'Select two dates for the signed difference, or enter an offset to find a new date from the starting date.','The difference excludes the starting day. Calendar dates are calculated independently of daylight saving changes. Supported years are 0001 through 9999.'],
 ['percentage-calculator','Percentage Calculator','Find a percentage of a number, percentage share, and percentage change instantly.',input('part','Percentage / part / original value','number','20')+input('whole','Number / whole / new value','number','100')+result,'Use the first result for discounts or proportions. The second result shows what share the first number represents of the second. The third compares the second number to the first.','Percentage change divides the difference by the absolute original value. Division by zero is undefined and is clearly marked.'],
 ['unit-converter','Length, Weight and Temperature Converter','Convert common length, weight and temperature units without uploading data.',select('unit-category','Measurement',[['length','Length'],['weight','Weight'],['temperature','Temperature']])+input('unit-value','Value','number','1')+select('unit-from','From',[])+select('unit-to','To',[])+result,'Choose length, weight or temperature, then select the input and output units. Results update as you type.','Length includes meters, kilometers, centimeters, millimeters, inches, feet, yards and miles. Weight includes kilograms, grams, pounds and ounces. Temperature supports Celsius, Fahrenheit and Kelvin. Values below absolute zero are rejected.'],
 ['password-generator','Random Password Generator','Generate a random password locally with secure browser randomness and customizable character groups.',input('password-length','Length (8–128)','number','20')+['uppercase','lowercase','numbers','symbols'].map(id=>`<label class="check"><input type="checkbox" id="${id}" checked> Include ${id}</label>`).join('')+action('generate','Generate password')+area('password-output','Generated password','',true)+action('copy-password','Copy password')+result,'Choose a length and character groups, then generate. Each selected group is represented at least once. Copy the password to your password manager.','Randomness comes from the Web Crypto API. Passwords are never sent to a server or saved by this site. Copying puts the password on your device clipboard; clipboard history may retain it.'],
 ['timer','Online Timer and Stopwatch','Run a countdown timer or stopwatch in your browser, with pause and reset controls.',select('timer-mode','Mode',[['countdown','Countdown'],['stopwatch','Stopwatch']])+input('timer-minutes','Countdown minutes (0.01–1440)','number','5')+`<output id="clock-display" class="clock-display" aria-live="off">05:00.0</output><div class="actions">${action('timer-start','Start')}${action('timer-pause','Pause')}${action('timer-reset','Reset')}</div>`+result,'Set the countdown duration or select Stopwatch. Start, pause and resume as needed. The countdown displays a completion message.','Keep this tab open. Browsers may delay background updates or suspend the device; this is not a dependable alarm. Elapsed time is calculated from the clock rather than counting update callbacks. No audio or notification permission is required.'],
 ['json-formatter','JSON Formatter and Validator','Validate, pretty-print and minify JSON locally with clear syntax errors.',area('json-input','JSON input','{"hello":"world","count":3}')+`<div class="actions">${action('json-format','Format JSON')}${action('json-minify','Minify JSON')}</div>`+area('json-output','JSON result','',true)+action('copy-json','Copy result')+result,'Paste JSON, then choose Format for indentation or Minify for compact output. Invalid JSON shows a syntax error and clears the previous result.','This tool uses the standard JavaScript JSON parser. Comments and trailing commas are invalid. Large integers beyond JavaScript precision may change; keep exact identifiers as quoted strings. Duplicate keys keep their last value.'],
 ['url-encoder','URL Encoder and Decoder','Encode and decode URL components, including Unicode text and percent escapes.',area('url-input','Text or encoded URL component','hello world')+`<div class="actions">${action('url-encode','Encode component')}${action('url-decode','Decode component')}</div>`+area('url-output','Result','',true)+action('copy-url','Copy result')+result,'Encode a value before putting it in a URL query parameter. Decode percent-encoded text to read it.','This uses encodeURIComponent and decodeURIComponent for a single component. Encoding an entire URL also encodes its separators. A plus sign stays a plus sign when decoding; form-style plus-to-space conversion is not applied.'],
 ['base64','Base64 Encoder and Decoder','Convert UTF-8 text to Base64 and decode Base64 back to text locally.',area('base64-input','Text or Base64','Hello, world!')+`<div class="actions">${action('base64-encode','Encode UTF-8')}${action('base64-decode','Decode UTF-8')}</div>`+area('base64-output','Result','',true)+action('copy-base64','Copy result')+result,'Paste text to encode its UTF-8 bytes, or paste standard Base64 to decode. Whitespace is ignored when decoding.','Base64 is an encoding, not encryption. It does not protect secrets. The decoder accepts standard padded Base64 and rejects binary output that is not valid UTF-8. URL-safe Base64 uses a different alphabet and is not supported.'],
 ['color-picker','HEX, RGB and HSL Color Converter','Choose a color or enter HEX to convert it into RGB and HSL color values.',input('color-visual','Choose a color','color','#3b775d')+input('color-hex','HEX color (#RGB or #RRGGBB)','text','#3b775d')+result,'Select a color visually or enter a three-digit or six-digit HEX code. Copy the resulting HEX, RGB and HSL values from the output.','Conversion uses the sRGB color model with rounded RGB and HSL values. Alpha transparency, named colors and wide-gamut colors are not supported.']
].map(([slug,title,description,body,how,limits])=>({slug,title,description,body,how,limits,host:`${slug}.util.oa.gg`}));
module.exports={tools};
