import {locale,translate} from './localize.js';
const $=id=>document.getElementById(id);
const tool=document.querySelector('[data-tool]')?.dataset.tool;
const fmt=n=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:8}):'Undefined';
const show=text=>{$('tool-result').textContent=translate(text);};
const number=id=>{if(!$(id).value.trim()||!Number.isFinite(Number($(id).value)))throw Error('Enter a finite number in every field.');return Number($(id).value);};
const guarded=fn=>()=>{try{fn();}catch(e){show(e.message);}};
const listen=(ids,fn)=>{ids.forEach(id=>$(id).addEventListener('input',guarded(fn)));guarded(fn)();};
const dateValue=value=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw Error('Choose a date in years 0001–9999.');const year=Number(value.slice(0,4));if(year<1)throw Error('Choose a date in years 0001–9999.');const n=Date.parse(value+'T00:00:00Z');if(!Number.isFinite(n)||new Date(n).toISOString().slice(0,10)!==value)throw Error('Choose a valid calendar date.');return n;};
const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
if(tool==='calendar'){
 const render=()=>{const v=$('month').value;if(!/^\d{4}-\d{2}$/.test(v)||Number(v.slice(0,4))<1){$('month-title').textContent='Choose a month in years 0001–9999.';$('calendar-grid').replaceChildren();return;}const first=new Date(v+'-01T12:00:00Z'),year=first.getUTCFullYear(),month=first.getUTCMonth(),last=new Date(first);last.setUTCMonth(month+1,0);const start=Number($('week-start').value),offset=(first.getUTCDay()-start+7)%7;
 $('month-title').textContent=first.toLocaleDateString(locale,{month:'long',year:'numeric',timeZone:'UTC'});const grid=$('calendar-grid');grid.replaceChildren();for(let i=0;i<7;i++){const cell=document.createElement('div');cell.setAttribute('role','columnheader');cell.textContent=translate(['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][(i+start)%7]);grid.append(cell);}for(let i=0;i<Math.ceil((offset+last.getUTCDate())/7)*7;i++){const day=i-offset+1,cell=document.createElement('div');cell.setAttribute('role','gridcell');if(day>0&&day<=last.getUTCDate()){cell.textContent=day;const value=`${v}-${String(day).padStart(2,'0')}`;if(value===localToday()){cell.className='today';cell.setAttribute('aria-label',translate(`${value}, today`));}}grid.append(cell);}};
 $('month').value=localToday().slice(0,7);$('month').min='0001-01';$('month').max='9999-12';['month','week-start'].forEach(id=>$(id).addEventListener('input',render));const move=amount=>{const d=new Date($('month').value+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+amount);if(d.getUTCFullYear()<1||d.getUTCFullYear()>9999)return;$('month').value=d.toISOString().slice(0,7);render();};$('previous').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('today').onclick=()=>{$('month').value=localToday().slice(0,7);render();};$('print').onclick=()=>window.print();render();
}
if(tool==='date-calculator'){
 $('date-start').value=$('date-end').value=localToday();listen(['date-start','date-end','date-offset'],()=>{const start=dateValue($('date-start').value),end=dateValue($('date-end').value),offset=number('date-offset');if(!Number.isSafeInteger(offset))throw Error('Days to add must be a whole number.');const added=new Date(start+offset*86400000);if(!Number.isFinite(added.getTime())||added.getUTCFullYear()<1||added.getUTCFullYear()>9999)throw Error('Result must be in years 0001–9999.');show(`Difference: ${fmt((end-start)/86400000)} days\nDate after ${fmt(offset)} days: ${added.toISOString().slice(0,10)}`);});
}
if(tool==='percentage-calculator')listen(['part','whole'],()=>{const a=number('part'),b=number('whole');show(`${fmt(a)}% of ${fmt(b)} = ${fmt((a/100)*b)}\n${fmt(a)} as a percentage of ${fmt(b)} = ${b===0?'Undefined':fmt(a/b*100)+'%'}\nChange from ${fmt(a)} to ${fmt(b)} = ${a===0?'Undefined':fmt((b-a)/Math.abs(a)*100)+'%'}`);});
if(tool==='unit-converter'){
 const units={length:{m:1,km:1000,cm:.01,mm:.001,in:.0254,ft:.3048,yd:.9144,mi:1609.344},weight:{kg:1,g:.001,lb:.45359237,oz:.028349523125},temperature:{C:1,F:1,K:1}};
 const update=()=>{const category=$('unit-category').value,v=number('unit-value'),from=$('unit-from').value,to=$('unit-to').value;let value;if(category==='temperature'){const c=from==='F'?(v-32)*5/9:from==='K'?v-273.15:v;if(c< -273.15-1e-10)throw Error('Temperature cannot be below absolute zero.');value=to==='F'?c*9/5+32:to==='K'?c+273.15:c;}else value=v*units[category][from]/units[category][to];if(!Number.isFinite(value))throw Error('Value is outside the calculation range.');show(`${fmt(v)} ${from} = ${fmt(value)} ${to}`);};
 const setup=()=>{const keys=Object.keys(units[$('unit-category').value]);['unit-from','unit-to'].forEach((id,index)=>{$(id).replaceChildren(...keys.map(key=>new Option(key,key)));$(id).selectedIndex=index;});guarded(update)();};$('unit-category').onchange=setup;setup();listen(['unit-value','unit-from','unit-to'],update);
}
const copy=(button,output)=>{$(button).onclick=async()=>{try{if(!$(output).value)throw Error('Generate a result first.');await navigator.clipboard.writeText($(output).value);show('Copied to clipboard.');}catch{show('Copy unavailable. Select the result and copy it manually.');}};};
if(tool==='password-generator'){
 const random=max=>{const limit=256-256%max;let v;do{v=crypto.getRandomValues(new Uint8Array(1))[0];}while(v>=limit);return v%max;};
 $('generate').onclick=guarded(()=>{const length=number('password-length');const groups=[['uppercase','ABCDEFGHIJKLMNOPQRSTUVWXYZ'],['lowercase','abcdefghijklmnopqrstuvwxyz'],['numbers','0123456789'],['symbols','!@#$%^&*()-_=+[]{}:,.?']].filter(([id])=>$(id).checked).map(([,chars])=>chars);if(!Number.isInteger(length)||length<8||length>128)throw Error('Choose a whole-number length from 8 to 128.');if(!groups.length)throw Error('Select at least one character group.');const alphabet=groups.join(''),chars=groups.map(g=>g[random(g.length)]);while(chars.length<length)chars.push(alphabet[random(alphabet.length)]);for(let i=chars.length-1;i>0;i--){const j=random(i+1);[chars[i],chars[j]]=[chars[j],chars[i]];}$('password-output').value=chars.join('');show('Generated locally. Store it in your password manager.');});copy('copy-password','password-output');
 ['password-length','uppercase','lowercase','numbers','symbols'].forEach(id=>$(id).oninput=()=>{$('password-output').value='';show('Generate a password using the new settings.');});
}
if(tool==='timer'){
 let running=false,elapsed=0,started=0,duration=300000;const current=()=>elapsed+(running?performance.now()-started:0);const render=()=>{const time=current(),countdown=$('timer-mode').value==='countdown',remaining=countdown?Math.max(0,duration-time):time;const tenths=Math.floor(remaining/100),minutes=Math.floor(tenths/600),seconds=Math.floor(tenths/10)%60;$('clock-display').textContent=`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}.${tenths%10}`;if(running&&countdown&&time>=duration){running=false;elapsed=duration;show('Time is up.');$('timer-start').disabled=false;}};
 const reset=guarded(()=>{running=false;elapsed=0;$('timer-start').disabled=false;duration=number('timer-minutes')*60000;if(duration<600||duration>86400000)throw Error('Choose 0.01 to 1440 minutes.');show('Ready. Keep this tab open.');render();});$('timer-reset').onclick=reset;$('timer-mode').onchange=reset;$('timer-minutes').oninput=reset;
 $('timer-start').onclick=guarded(()=>{if(running)return;if($('timer-mode').value==='countdown'){duration=number('timer-minutes')*60000;if(duration<600||duration>86400000)throw Error('Choose 0.01 to 1440 minutes.');if(elapsed>=duration)elapsed=0;}started=performance.now();running=true;$('timer-start').disabled=true;show('Running.');render();});$('timer-pause').onclick=()=>{elapsed=current();running=false;$('timer-start').disabled=false;show('Paused.');render();};setInterval(render,100);reset();
}
if(['json-formatter','url-encoder','base64'].includes(tool)){
 const prefix=tool==='json-formatter'?'json':tool==='url-encoder'?'url':'base64';const transform=fn=>()=>{try{$(prefix+'-output').value=fn($(prefix+'-input').value);show('Done. Result stays in this browser.');}catch(e){$(prefix+'-output').value='';show(`Invalid input: ${e.message}`);}};
 if(prefix==='json'){$('json-format').onclick=transform(v=>JSON.stringify(JSON.parse(v),null,2));$('json-minify').onclick=transform(v=>JSON.stringify(JSON.parse(v)));}
 if(prefix==='url'){$('url-encode').onclick=transform(encodeURIComponent);$('url-decode').onclick=transform(decodeURIComponent);}
 if(prefix==='base64'){$('base64-encode').onclick=transform(v=>{const bytes=new TextEncoder().encode(v);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary);});$('base64-decode').onclick=transform(v=>{const clean=v.replace(/\s/g,'');if(!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(clean))throw Error('Use standard padded Base64.');const bytes=Uint8Array.from(atob(clean),c=>c.charCodeAt(0));return new TextDecoder('utf-8',{fatal:true}).decode(bytes);});}copy('copy-'+prefix,prefix+'-output');
 $(prefix+'-input').oninput=()=>{$(prefix+'-output').value='';show('Input changed. Choose an action to update the result.');};
}
if(tool==='color-picker'){
 const render=()=>{let hex=$('color-hex').value.trim();if(!/^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(hex))throw Error('Enter #RGB or #RRGGBB.');if(hex.length===4)hex='#'+[...hex.slice(1)].map(c=>c+c).join('');hex=hex.toLowerCase();$('color-visual').value=hex;const rgb=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)),[r,g,b]=rgb.map(n=>n/255),max=Math.max(r,g,b),min=Math.min(r,g,b),delta=max-min,l=(max+min)/2;let h=0,s=0;if(delta){s=delta/(1-Math.abs(2*l-1));h=(max===r?(g-b)/delta%6:max===g?(b-r)/delta+2:(r-g)/delta+4)*60;if(h<0)h+=360;}show(`HEX: ${hex}\nRGB: rgb(${rgb.join(', ')})\nHSL: hsl(${Math.round(h)}, ${Math.round(s*100)}%, ${Math.round(l*100)}%)`);};$('color-visual').oninput=()=>{$('color-hex').value=$('color-visual').value;guarded(render)();};listen(['color-hex'],render);
}
